# -*- coding: utf-8 -*-
"""ML_project_MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idDGHWhPISFG_EWrhkcftrIAYODyPx2H

구글 드라이브 마운트
"""

from google.colab import drive
drive.mount('/content/drive')

"""라이브러리 설치"""

# install library
!pip install selenium pandas numpy scikit-learn matplotlib seaborn tslearn scipy

# Import Library
## Basic
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import time
import os
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.notebook import tqdm #진행률 표시
import sys
import urllib.request
from urllib.request  import urlretrieve

## 전처리 및 특징 엔지니어링
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

## 시계열 데이터 군집화
from tslearn.clustering import TimeSeriesKMeans
from tslearn.metrics import dtw # Dynamic Time Warping
from tslearn.preprocessing import TimeSeriesScalerMeanVariance

## 통계 분석
from scipy.stats import pearsonr, spearmanr # 상관계수

## matplotlib 한글 폰트 설정
plt.rcParams['font.family'] = 'AppleGothic' # Mac
      # plt.rcParams['font.family'] = 'Malgun Gothic' # Windows
plt.rcParams['axes.unicode_minus'] = False # 한글 폰트 사용시 마이너스 폰트 깨짐 해결

# Commented out IPython magic to ensure Python compatibility.
!apt-get install -y fonts-nanum*
!rm -rf /root/.cache/matplotlib/* # 폰트 캐시 재설정
# 런타임 다시 시작 후 실행
# %matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
#
path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
font_name = mpl.font_manager.FontProperties(fname=path).get_name()
plt.rcParams['font.family'] = font_name

"""설명변수와 타겟변수의 관계 분석"""

# 범주형 설명 변수 vs. 목표 변수 (박스 플롯)
plt.figure(figsize=(12, 7))
sns.boxplot(x='출발요일', y='검색일로부터 며칠 전', data=df_2_1, order=['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일'])
plt.title('출발 요일별 최적 구매 시점 분포')
plt.xlabel('출발 요일')
plt.ylabel('검색일로부터 며칠 전')
plt.show()

plt.figure(figsize=(15, 8))
sns.boxplot(x='대륙/지역', y='검색일로부터 며칠 전', data=df_2_1)
plt.title('대륙/지역별 최적 구매 시점 분포')
plt.xlabel('대륙/지역')
plt.ylabel('검색일로부터 며칠 전')
plt.xticks(rotation=45)
plt.show()

# 수치형 설명 변수 vs. 목표 변수 (산점도)
plt.figure(figsize=(10, 6))
sns.scatterplot(x='최소가격', y='검색일로부터 며칠 전', data=df_2_1)
plt.title('최소가격과 최적 구매 시점 관계')
plt.xlabel('최소가격 (원)')
plt.ylabel('검색일로부터 며칠 전')
plt.show()

"""데이터 불러오기 & 전처리"""

# Import data
import pandas as pd

df_1_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_1_1_table.csv',sep = "|")
df_1_2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_1_2_table.csv', sep = "|")
df_2_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_2_1_table.csv', sep = "|")
df_2_2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_2_2_table.csv', sep = "|")
df_2_3 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_2_3_table.csv', sep = "|")

arrival_airports = {
    "일본": ["NRT", "KIX", "FUK"],
    "중국": ["PVG", "PEK", "TAO"],
    "동북아시아_기타": ["TPE", "HKG", "UBN"],
    "동남아시아": ["BKK", "DAD", "HAN", "SIN"],
    "서유럽": ["LHR", "CDG", "FRA", "AMS", "ZRH"],
    "남유럽": ["FCO", "BCN", "LIS"],
    "동유럽": ["PRG", "BUD", "WAW", "VIE"],
    "북유럽": ["HEL", "CPH"],
    "미국_서부": ["LAX", "SFO", "LAS"],
    "미국_동부": ["JFK", "EWR", "BOS"],
    "캐나다": ["YVR", "YYZ"],
    "오세아니아":["GUM","SYD","HNL"]
}

# 컬럼명 통일
df_1_1.rename(columns={'도착공항': '목적지'}, inplace=True)

# 날짜 형식 변환
df_1_1['검색일'] = pd.to_datetime(df_1_1['검색일'])
df_1_2['검색일'] = pd.to_datetime(df_1_2['검색일'])
df_2_1['검색일'] = pd.to_datetime(df_2_1['검색일'])
df_2_2['검색일'] = pd.to_datetime(df_2_2['검색일'])
df_2_3['검색일'] = pd.to_datetime(df_2_3['검색일'])

df_1_1['출발일'] = pd.to_datetime(df_1_1['출발일'])
df_1_2['출발일'] = pd.to_datetime(df_1_2['출발일'])
df_2_1['출발일'] = pd.to_datetime(df_2_1['출발일'])
df_2_2['출발일'] = pd.to_datetime(df_2_2['출발일'])
df_2_3['출발일'] = pd.to_datetime(df_2_3['출발일'])

df_2_1['구매일'] = pd.to_datetime(df_2_1['구매일'])
df_2_2['구매일'] = pd.to_datetime(df_2_2['구매일'])

df_1_1['label'] = (df_1_1['출발일'] - df_1_1['검색일']).dt.days
df_2_1['label'] = (df_2_1['출발일'] - df_2_1['구매일']).dt.days

cols_A = ['검색일', '출발일', '목적지', '대륙/지역','저장시간', '데이터 유형','가격','label']
df_1_1_A = df_1_1[cols_A]
df_2_1_A = df_2_1.rename(columns={'최소가격': '가격'})[cols_A]

main_data_A = pd.concat([df_1_1_A, df_2_1_A], ignore_index=True)

dfs = [df_1_1, df_1_2, df_2_1, df_2_2, df_2_3]
for i in dfs:
  print(i.columns)

for i in dfs:
  print(i)

"""###한글 폰트 설치"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'

# FontProperties 객체 생성
font_prop = fm.FontProperties(fname=font_path)

# Matplotlib 기본 폰트 설정
plt.rcParams['font.family'] = font_prop.get_name()
plt.rcParams['axes.unicode_minus'] = False # 마이너스 기호 깨짐 방지

"""###label의 분포 시각화"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


# label 분포
sns.histplot(main_data_A['label'], bins=50, kde=True)
plt.title("label 분포")
plt.xlabel("label (일)")
plt.ylabel("빈도")
plt.show()

"""###데이터 전처리"""

from sklearn.preprocessing import OneHotEncoder

# 출발시간, 도착시간 >> 출발시간대, 도착시간대
def timeslot(time_data):
  if pd.isnull(time_data): return "NULL"
  if 0 <= int(time_data.split(':')[0]) < 6:
    return "새벽"
  elif 6 <= int(time_data.split(':')[0]) < 12:
    return '오전'
  elif 12 <= int(time_data.split(':')[0]) < 18:
    return '오후'
  else:
    return '저녁'

df_1_1['출발시간대'] = df_1_1['출발시간_24시'].apply(timeslot)
df_1_1['도착시간대'] = df_1_1['도착시간_24시'].apply(timeslot)

df_encoded = pd.get_dummies(df_1_1, columns=['출발시간대', '도착시간대'])

# FSC/LCC

from sklearn.cluster import KMeans
fsc_lcc = []

# '목적지' column 기준으로 그룹화
group_by_arrival = df_1_1.groupby('목적지')

# 각 '목적지'에 대한 K-Means 클러스터링 수행
for airport, info in group_by_arrival:
  print(f"\n--- Processing Arrival Airport: {airport} ---")
  km = KMeans(n_clusters=2, random_state=0).fit(info[['가격']])
  upper_price_cluster = int(km.cluster_centers_[1] > km.cluster_centers_[0])
  print(f"FSC: {upper_price_cluster}")
  info_copy = info.copy()
  info_copy['FSC/LCC'] = ['FSC' if lbl == upper_price_cluster else 'LCC' for lbl in km.labels_]
  fsc_lcc.append(info_copy)

df_1_1 = pd.concat(fsc_lcc, ignore_index=True)

"""###조절변수와 label의 연관분석"""

import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# 요일별 label 분포
sns.boxplot(x='출발요일', y= 'label', data = df_1_1)
plt.title("요일별 label 분포")
plt.xlabel("출발요일")
plt.ylabel("label (일)")
plt.show()

"""비행시간/거리와 label의 연관분석"""

sns.lmplot(x='비행시간_분', y='label', data=df_1_1, line_kws={'color': 'orange'})
plt.title("비행시간과 label(최적 구매 시점)의 관계")
plt.xlabel("비행시간 (분)")
plt.ylabel("label")
plt.show()

# 상관계수 확인
corr = df_1_1[['비행시간_분', 'label']].corr().iloc[0,1]
print(f"상관계수: {corr:.3f}")

"""경유여부와 label의 연관분석"""

sns.boxplot(x='경유여부', y='label', data=df_1_1)
plt.title("경유여부와 label(최적 구매 시점)의 관계")
plt.xlabel("경유여부")
plt.ylabel("label")
plt.show()

"""출발시간대/도착시간대와 label의 연관분석"""

# 출발 시간대별
sns.boxplot(x='출발시간대', y='label', data=df_1_1, order=['새벽','오전','오후','저녁'])
plt.title("출발시간대에 따른 label 차이")
plt.show()

# 도착 시간대별
sns.boxplot(x='도착시간대', y='label', data=df_1_1, order=['새벽','오전','오후','저녁'])
plt.title("도착시간대에 따른 label 차이")
plt.show()

"""대륙/지역과 label의 연관분석"""

plt.figure(figsize=(10, 5))
sns.boxplot(x='대륙/지역', y='label', data=df_1_1)
plt.xticks(rotation=45)
plt.title("대륙/지역별 label 분포")
plt.show()

"""FSC/LCC와 label의 연관분석"""

sns.boxplot(x='FSC/LCC', y='label', data=df_1_1)
plt.title("FSC / LCC에 따른 label 차이")
plt.show()

"""###수치형 데이터 사이 상관관계 분석"""

num_cols = ['가격','비행시간_분', 'label']
df_corr = df_1_1[num_cols].corr()
print(df_corr)

sns.heatmap(df_1_1[num_cols].corr(), annot=True, cmap='coolwarm')
plt.title('수치형 변수 상관관계')
plt.show()
# 선형 회귀 모델로는 예측력이 떨어짐을 확인
# 비선형 회귀 모델이 필요

# 분산 팽창 계수 VIF

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import StandardScaler

X_num = df_1_1[num_cols].dropna()
X_scaled = StandardScaler().fit_transform(X_num)

vif_df = pd.DataFrame()
vif_df["VIF Factor"] = [variance_inflation_factor(X_scaled, i) for i in range(X_scaled.shape[1])]
vif_df["features"] = X_num.columns
print(vif_df)

# 조건수
condition_number = np.linalg.cond(X_scaled)
print(f"조건수 (Condition Number): {condition_number:.2f}")

# 다중 공선성 분석 결과, 다중공선성은 유의미하지 않은 것으로 확인

"""### 범주형 데이터의 label 분포 ###"""

cat_cols = ['출발요일', '출발시간대','도착시간대', '경유여부', '대륙/지역', 'FSC/LCC']

def distribution_category(var, order=None):
    plt.figure(figsize=(10, 4))
    sns.histplot(data=df_1_1, x='가격', hue=var, kde=True, stat='density', multiple='stack', palette='Set2', hue_order=order)
    plt.title(f"{var}에 따른 항공권 가격 분포")
    plt.xlabel("항공권 가격")
    plt.show()
# 분포 시각화
distribution_category('출발요일')
distribution_category('경유여부')
distribution_category('출발시간대', order=['새벽','오전','오후','저녁'])
distribution_category('도착시간대', order=['새벽','오전','오후','저녁'])
distribution_category('대륙/지역')
distribution_category('FSC/LCC')

# 정규성 검정
from scipy.stats import shapiro

# 결과 저장용 리스트
results = []

# 변수별 루프
for var in cat_cols:
    print(f"\n === 정규성 검정 - {var} ===")
    for cat, group in df_1_1.groupby(var):
        price = group['가격'].dropna()
        if len(price) < 3:
            print(f"  - {cat}: 샘플 부족 ({len(price)}개)")
            continue
        stat, p = shapiro(price)
        normal = '정규분포 만족' if p >= 0.05 else '비정규분포'
        print(f"  - {cat}: p = {p:.4f} → {normal}")
        results.append({
            '변수': var,
            '범주': cat,
            '샘플 수': len(price),
            'p-value': round(p, 4),
            '결과': normal
        })

result_df = pd.DataFrame(results)
print(result_df)

# 전부 다 비정규분포로 확인

# 평균 차이 유의성 검정
# Kruskal-Wallis
from scipy.stats import kruskal

for var in cat_cols:
    groups = [g['가격'].dropna() for _, g in df_1_1.groupby(var) if len(g) > 10]
    if len(groups) >= 2:
        stat, p = kruskal(*groups)
        print(f"{var} → 가격: p-value = {p:.4f}")

# 모두 유의미한 변수로 확인

"""### 데이터 파이프라인 및 데이터 분리"""

print(df_1_1.columns)
print(num_cols)
print(cat_cols)

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_feat = [col for col in num_cols if col != 'label']
features = num_feat + cat_cols

X = df_1_1[features]
y = df_1_1['label']

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_feat),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])

X_processed = preprocessor.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state = 32)

"""### 모델 정의"""

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor

models = {
    'Random Forest': RandomForestRegressor(n_estimators = 100, random_state = 0),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators= 100, random_state = 0),
    'XGBoost': XGBRegressor(n_estimators= 100, random_state = 0),
    'LightGBM': LGBMRegressor(n_estimators= 100, random_state = 0),
    'MLP Regressor': MLPRegressor(hidden_layer_sizes=(64,32), max_iter=300, random_state = 0),
    'KNN Regressor': KNeighborsRegressor(n_neighbors=5)
}

"""### 모델 반복 학습 및 평가"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

model_results = []

for name, model in models.items():
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  mae = mean_absolute_error(y_test, y_pred)
  rmse = np.sqrt(mean_squared_error(y_test, y_pred))
  r2 = r2_score(y_test, y_pred)

  model_results.append({'모델': name, 'MAE': round(mae,2), 'RMSE': round(rmse,2), 'R2': round(r2,3)})

  # 시각화
  plt.figure(figsize=(5,3))
  plt.bar(['MAE','RMSE','R2'], [mae, rmse, r2])
  plt.title(f'{name} 성능 지표')
  plt.ylabel('Score')
  for i, v in enumerate([mae, rmse, r2]):
    plt.text(i, v + 0.01*max(mae,rmse,r2), f'{v:.3f}', ha='center')
  plt.ylim(0, max(mae, rmse, r2)*1.2)
  plt.show()

model_results_df = pd.DataFrame(model_results)
print(model_results_df)


# <성능지표>
# RMSE: 가장 낮은값
# R^2: 0.6 - 0.8 이상이면 좋은 성능
# MAE: 작을수록 좋음
# 학습시간


# <결과 해석>
# MAE: 예측값과 실제 label의 평균 절대 오차
# >> 약 16~ 18일 오차발생

# R^2: 약 87%의 설명력

# <모델 선정>
# Random Forest & XGBoost

"""### Feature Importance 해석"""

valid_models = ['Random Forest', 'XGBoost']

feature_names = preprocessor.get_feature_names_out()

for name in valid_models:
  model = models[name]
  model.fit(X_train, y_train)
  importances = model.feature_importances_ if hasattr(model, 'feature_importances_') else None


  if importances is not None:
    # 중요도 내림차순 정렬
    indices = np.argsort(importances)[::-1]
    top_n = 20  # 상위 N개 feature 시각화

    # 시각화
    plt.figure(figsize=(10, 5))
    plt.barh(range(top_n), importances[indices[:top_n]][::-1], align='center')
    plt.yticks(range(top_n), [feature_names[i] for i in indices[:top_n]][::-1])
    plt.xlabel('Importance Score')
    plt.title(f'{name} - Feature Importance')
    plt.tight_layout()
    plt.show()

    # 중요도 수치 출력
    top_features = [(feature_names[i], importances[i]) for i in indices[:top_n]]
    print(f"\n🔍 {name} - 중요 변수 Top {top_n}:")
    for feat, score in top_features:
        print(f"{feat:<30} → {score:.4f}")
  else:
        print(f"{name}은 feature_importances_ 속성이 없습니다.")

"""##### 최저가 발생 시점 분석 (df_1_1 & df_2_1)"""

# 날짜 변환
df_1_1['출발일'] = pd.to_datetime(df_1_1['출발일'])
df_1_1['검색일'] = pd.to_datetime(df_1_1['검색일'])
df_2_1['출발일'] = pd.to_datetime(df_2_1['출발일'])
df_2_1['구매일'] = pd.to_datetime(df_2_1['구매일'])

# 출발일, 목적지 기준 병합
merged = pd.merge(df_1_1, df_2_1, on=['출발일', '목적지'], suffixes=('_현재', '_최소'))

# 최저가 발생 시점 (출발일까지 남은 일수)
merged['label'] = (merged['출발일'] - merged['구매일']).dt.days

# 시각화
import matplotlib.pyplot as plt
plt.hist(merged['label'], bins=30)
plt.title("최저가 발생 시점 분포")
plt.xlabel("출발일 기준 며칠 전")
plt.ylabel("건수")
plt.show()

# 최저가 발생 시점 통계 요약
print(merged['label'].describe())

# 최빈값 확인
mode_val = merged['label'].mode().iloc[0]
print(f"\n최저가가 가장 많이 발생한 일수(최빈값): {mode_val}일 전")

# 상위 10개의 최저가 발생 일수 + 건수
value_counts = merged['label'].value_counts().sort_values(ascending=False).head(10)
print("\n🔝 최저가가 가장 많이 발생한 상위 10개 시점 (출발일 기준 며칠 전):")
print(value_counts)

"""##### 시계열 데이터 군집화 (df_1_2 & df_2_2)"""

df_1_2['출발일'] = pd.to_datetime(df_1_2['출발일'])
df_1_2['검색일'] = pd.to_datetime(df_1_2['검색일'])
df_2_2['출발일'] = pd.to_datetime(df_2_2['출발일'])
df_2_2['구매일'] = pd.to_datetime(df_2_2['구매일'])

df_1_2['label'] = (df_1_2['출발일'] - df_1_2['검색일']).dt.days
df_2_2['label'] = (df_2_2['출발일'] - df_2_2['구매일']).dt.days

# 항공편 정보(출발일+도착지)
df_1_2['indicator'] = df_1_2['출발일'].astype(str) + "_" + df_1_2['목적지']
df_2_2['indicator'] = df_2_2['출발일'].astype(str) + "_" + df_2_2['목적지']

# pivot 생성
# 미래 기준 (검색일 → 출발일까지)
pivot_future = df_1_2.pivot_table(
    index='indicator',
    columns='label',
    values='가격'
).sort_index(axis=1)

# 과거 기준 (출발일 ← 검색일)
pivot_past = df_2_2.pivot_table(
    index='indicator',
    columns='label',
    values='가격'
).sort_index(axis=1)

# row-wise Z-score 정규화
pivot_future_scaled = pivot_future.apply(lambda row: (row - row.mean()) / row.std(), axis=1)
pivot_past_scaled = pivot_past.apply(lambda row: (row - row.mean()) / row.std(), axis=1)

# 1-2 & 2-2 병합
common_ids = pivot_future_scaled.index.intersection(pivot_past_scaled.index)

merged_scaled = pd.concat([
    pivot_future_scaled.loc[common_ids],
    pivot_past_scaled.loc[common_ids]
], axis=1).dropna()

# 군집화 & 시각화
kmeans = KMeans(n_clusters=4, random_state=42)
merged_scaled['cluster'] = kmeans.fit_predict(merged_scaled)

# 군집별 평균 시계열 시각화
cluster_avg = merged_scaled.groupby('cluster').mean()

plt.figure(figsize=(12, 6))
for c in cluster_avg.index:
    plt.plot(cluster_avg.columns, cluster_avg.loc[c], label=f'Cluster {c}')
plt.title("시계열 군집화 결과 (df_1_2 & df_2_2 정규화 후 병합)")
plt.xlabel("출발일까지 남은 일수 (왼쪽: 미래 df_1_2 | 오른쪽: 과거 df_2_2)")
plt.ylabel("Z-score 정규화된 가격")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

